version: '3.9'

#services:
#  db:
#    image: postgres
#
#  web:
#    build: .
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8000:8000"

services:
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
#        - .:/usr/src/app/
        - .:/code
      env_file:
        - ./.env
      ports:
        - '8000:8000'
      depends_on:
        - db

    db:
      image: postgres
      restart: always
#      ports:
#        - '5432'
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        POSTGRESS_USER: postgres
        POSTGRESS_PASSWORD: postgres
        POSTGRES_DB: postgres
#        POSTGRES_HOST_AUTH_METHOD: 'trust'


