# Generated by Django 3.2.8 on 2022-01-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0004_auto_20211214_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewOfSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sport', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['type_sport'],
            },
        ),
    ]
