# Generated by Django 3.2.8 on 2022-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_viewofsport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_second_name', models.CharField(max_length=100)),
                ('coach_surname', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['coach_surname'],
            },
        ),
    ]
