# Generated by Django 3.2.8 on 2022-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='viewofsport',
            name='type_sport',
            field=models.CharField(max_length=100, verbose_name='Вид спорта/услуги'),
        ),
    ]
