# Generated by Django 3.2.8 on 2022-01-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20220126_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['coach_surname'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренера'},
        ),
        migrations.AlterModelOptions(
            name='viewofsport',
            options={'ordering': ['type_sport'], 'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
    ]
