# Generated by Django 3.2.8 on 2022-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20220126_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['short_name'],
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='img',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото (имя файла)'),
        ),
        migrations.AddField(
            model_name='coach',
            name='imgPath',
            field=models.FilePathField(blank=True, verbose_name='Photo Path'),
        ),
    ]
