# Generated by Django 3.2.8 on 2022-01-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20220126_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='img',
            field=models.FileField(blank=True, upload_to='license', verbose_name='Фото (имя файла)'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='imgPath',
            field=models.FilePathField(path='assets/img/coach_org'),
        ),
    ]
