# Generated by Django 3.2.8 on 2022-01-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_coach_imgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='imgPath',
        ),
    ]
