# Generated by Django 3.2.8 on 2022-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_coach_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='imgAdd',
            field=models.FileField(blank=True, upload_to='staticfiles/img/coach_org', verbose_name='Добавить фото'),
        ),
        migrations.AddField(
            model_name='coach',
            name='imgChoice',
            field=models.FilePathField(blank=True, path='staticfiles/img/coach_org', verbose_name='Выбрать фото'),
        ),
    ]
