# Generated by Django 3.2.8 on 2022-01-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_coach_imgadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabsSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.viewofsport')),
            ],
            options={
                'verbose_name': 'Вкладка виды спорта',
                'ordering': ['type_sport'],
            },
        ),
    ]
