# Generated by Django 3.2.8 on 2022-01-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_tabssport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeListCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ManyToManyField(to='homepage.Organization')),
                ('type_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.viewofsport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Расписание тренера',
                'verbose_name_plural': 'Расписание тренеров',
                'ordering': ['type_sport'],
            },
        ),
        migrations.DeleteModel(
            name='TabsSport',
        ),
    ]
