# Generated by Django 3.2.8 on 2022-01-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20220126_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес объекта')),
            ],
            options={
                'verbose_name': 'Адрес объекта',
                'verbose_name_plural': 'Адреса объектов',
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='timelistcoach',
            name='d_week',
            field=models.CharField(blank=True, choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=11, verbose_name='День недели'),
        ),
        migrations.RemoveField(
            model_name='timelistcoach',
            name='coach',
        ),
        migrations.AddField(
            model_name='timelistcoach',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.coach', verbose_name='Тренер'),
        ),
    ]
