# Generated by Django 3.2.8 on 2022-01-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20220126_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelistcoach',
            options={'ordering': ['coach', 'type_sport', 'address', 'd_week'], 'verbose_name': 'Расписание тренера', 'verbose_name_plural': 'Расписание тренеров'},
        ),
        migrations.AddField(
            model_name='timelistcoach',
            name='d_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], default='Пн', max_length=11, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='timelistcoach',
            name='time_list',
            field=models.TextField(default='расписание пока не сформировано', max_length=200, verbose_name='Расписание'),
        ),
    ]
