# Generated by Django 3.2.8 on 2022-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20220126_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelistcoach',
            name='time_list',
            field=models.TextField(blank=True, max_length=200, verbose_name='Расписание'),
        ),
    ]
