# Generated by Django 3.2.8 on 2022-01-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_alter_timelistcoach_time_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группы ПФОЦ',
                'verbose_name_plural': 'Группа',
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='timelistcoach',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.group'),
        ),
    ]
