# Generated by Django 3.2.8 on 2022-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20220126_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewofsport',
            name='content',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание'),
        ),
    ]
