# Generated by Django 3.2.8 on 2022-01-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_alter_viewofsport_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelistcoach',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.group'),
        ),
    ]
