# Generated by Django 3.2.8 on 2022-01-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_alter_timelistcoach_d_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelistcoach',
            options={'ordering': ['coach', 'group', 'd_week', 'type_sport', 'address'], 'verbose_name': 'Расписание тренера', 'verbose_name_plural': 'Расписание тренеров'},
        ),
        migrations.CreateModel(
            name='TimeListOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_week', models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], default=0, max_length=11, verbose_name='День недели')),
                ('time_list', models.TextField(blank=True, max_length=200, verbose_name='Расписание')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.objectaddres', verbose_name='Адрес')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.organization', verbose_name='Организация')),
                ('type_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.viewofsport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Расписание тренера',
                'verbose_name_plural': 'Расписание тренеров',
                'ordering': ['organization', 'd_week', 'type_sport', 'address'],
            },
        ),
    ]
