# Generated by Django 3.2.8 on 2022-01-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_auto_20220128_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelistorganization',
            options={'ordering': ['organization', 'd_week', 'type_sport', 'address'], 'verbose_name': 'Расписание организаций', 'verbose_name_plural': 'Расписание организации'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Полное наименование'),
        ),
        migrations.CreateModel(
            name='SliderViewsOfSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_block', models.CharField(blank=True, max_length=50, null=True, verbose_name='Левый блок')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('sign', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подпись')),
                ('content', models.TextField(max_length=100, null=True, verbose_name='Текст')),
                ('bottom_block', models.CharField(blank=True, max_length=20, null=True, verbose_name='Нижний блок')),
                ('type_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.viewofsport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Слайд вид спорта',
                'verbose_name_plural': 'Слайды виды спорта',
                'ordering': ['type_sport'],
            },
        ),
    ]
