# Generated by Django 3.2.8 on 2022-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_auto_20220129_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderviewsofsport',
            name='imgAdd',
            field=models.ImageField(blank=True, upload_to='staticfiles/img/object-photo', verbose_name='Добавить фото'),
        ),
        migrations.AddField(
            model_name='sliderviewsofsport',
            name='imgChoice',
            field=models.FilePathField(blank=True, path='staticfiles/img/object-photo', verbose_name='Выбрать фото'),
        ),
    ]
