# Generated by Django 3.2.8 on 2022-01-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_alter_sliderviewsofsport_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsObject',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.objectaddres', verbose_name='Адрес Объекта')),
                ('front_title', models.CharField(max_length=50, null=True, verbose_name='Лицевой заголовок')),
                ('front_text', models.CharField(max_length=30, null=True, verbose_name='Лицевой текст')),
                ('inside_title', models.CharField(max_length=35, null=True, verbose_name='Внутренний заголовок')),
                ('inside_text', models.TextField(max_length=110, null=True, verbose_name='Внутренний текст')),
                ('imgAdd', models.ImageField(blank=True, upload_to='staticfiles/media/card_obj', verbose_name='Добавить медиа')),
                ('imgChoice', models.FilePathField(blank=True, path='staticfiles/media/card_obj', verbose_name='Выбрать медиа')),
                ('t_work_wd', models.CharField(max_length=30, null=True, verbose_name='Рабочие дни')),
                ('t_work_wh', models.CharField(max_length=30, null=True, verbose_name='Время работы рабочие дни')),
                ('t_work_hd', models.CharField(max_length=30, null=True, verbose_name='Выходные дни')),
                ('t_work_hh', models.CharField(max_length=30, null=True, verbose_name='Время работы выходные дни')),
            ],
            options={
                'verbose_name': 'Карточка объекта',
                'verbose_name_plural': 'Карточки объектов',
                'ordering': ['obj'],
            },
        ),
        migrations.CreateModel(
            name='CardsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Лицевой заголовок')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Текст')),
                ('price_f_color', models.CharField(max_length=10, null=True, verbose_name='Выделенный текст')),
                ('price_f_1', models.CharField(max_length=7, null=True, verbose_name='Стоимость полн. 1')),
                ('price_f_label_1', models.CharField(max_length=5, null=True, verbose_name='Стоим. полн. 1 ед. изм.')),
                ('price_f_2', models.CharField(max_length=7, null=True, verbose_name='Стоимость полн. 2')),
                ('price_f_label_2', models.CharField(max_length=5, null=True, verbose_name='Стоим. полн. 2 ед. изм.')),
                ('price_f_3', models.CharField(max_length=7, null=True, verbose_name='Стоимость полн. 3')),
                ('price_f_label_3', models.CharField(max_length=5, null=True, verbose_name='Стоим. полн. 3 ед. изм.')),
                ('price_f_4', models.CharField(max_length=7, null=True, verbose_name='Стоимость полн. 4')),
                ('price_f_label_4', models.CharField(max_length=5, null=True, verbose_name='Стоим. полн. 4 ед. изм.')),
                ('price_f_5', models.CharField(max_length=7, null=True, verbose_name='Стоимость полн. 5')),
                ('price_f_label_5', models.CharField(max_length=5, null=True, verbose_name='Стоим. полн. 5 ед. изм.')),
                ('imgAdd', models.ImageField(blank=True, upload_to='staticfiles/img/prices', verbose_name='Добавить медиа')),
                ('imgChoice', models.FilePathField(blank=True, path='staticfiles/img/prices', verbose_name='Выбрать медиа')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.objectaddres', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Стоимость услуги',
                'verbose_name_plural': 'Прайсы на услуги',
                'ordering': ['obj', 'title'],
            },
        ),
    ]
