# Generated by Django 3.2.8 on 2022-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_auto_20220129_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsprices',
            name='price_f_color',
            field=models.CharField(max_length=12, null=True, verbose_name='Красный текст полн. стоим. (напр. льготный)'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_l_color',
            field=models.CharField(max_length=12, null=True, verbose_name='Красный текст льг. стоим. (напр. льготный)'),
        ),
    ]
