# Generated by Django 3.2.8 on 2022-01-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_auto_20220129_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_1',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_2',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_3',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_4',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_label_1',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_label_2',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_label_3',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_f_label_4',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_1',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_2',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_3',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_4',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_label_1',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_label_2',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_label_3',
        ),
        migrations.RemoveField(
            model_name='cardsprices',
            name='price_l_label_4',
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f',
            field=models.CharField(blank=True, help_text='Полная стоимость услуги за одну единицу, например: за 1 ч, 1 день, 1 сутки', max_length=7, null=True, verbose_name='Полная стоимость'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_label',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Ярлык полной стоимости'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l',
            field=models.CharField(blank=True, help_text='Льготная стоимость услуги за одну единицу, например: за 1 ч, 1 день, 1 сутки', max_length=7, null=True, verbose_name='Льготная стоимость'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_label',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Ярлык льготной стоимости'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='description',
            field=models.TextField(help_text='Например: что входит в стоимость услуги', max_length=300, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_f_color',
            field=models.CharField(help_text='Текст под полной стоимостью будет выделен красным цветом', max_length=12, null=True, verbose_name='Особый текст'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_l_color',
            field=models.CharField(help_text='Текст под льготной стоимостью будет выделен красным цветом', max_length=12, null=True, verbose_name='Особый текст'),
        ),
    ]
