# Generated by Django 3.2.8 on 2022-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_auto_20220130_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_2',
            field=models.CharField(blank=True, help_text='Полная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость полн. 2'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_3',
            field=models.CharField(blank=True, help_text='Полная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость полн. 3'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_4',
            field=models.CharField(blank=True, help_text='Полная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость полн. 4'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_label_2',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. полн. 2 ед. изм.'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_label_3',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. полн. 3 ед. изм.'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_f_label_4',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. полн. 4 ед. изм.'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_2',
            field=models.CharField(blank=True, help_text='Льготная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость льгот. 2'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_3',
            field=models.CharField(blank=True, help_text='Льготная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость льгот. 3'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_4',
            field=models.CharField(blank=True, help_text='Льготная стоимость услуги за одну единицу, например: за 1,5ч, 2ч, 3ч', max_length=7, null=True, verbose_name='Стоимость льгот. 4'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_label_2',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. льгот. 2 ед. изм.'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_label_3',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. льгот. 3 ед. изм.'),
        ),
        migrations.AddField(
            model_name='cardsprices',
            name='price_l_label_4',
            field=models.CharField(blank=True, help_text='Единица измерения оплачиваемого времени, например: руб./ч., руб./день', max_length=5, null=True, verbose_name='Стоим. льгот. 4 ед. изм.'),
        ),
    ]
