# Generated by Django 3.2.8 on 2022-01-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_auto_20220130_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsprices',
            name='price_f_color',
            field=models.CharField(blank=True, help_text='Текст под полной стоимостью будет выделен красным цветом', max_length=12, null=True, verbose_name='Особый текст'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_f_label',
            field=models.CharField(blank=True, default='р/ч', help_text='Единица измерения оплачиваемого времени, например: р/ч, р/д', max_length=5, null=True, verbose_name='Ярлык полной стоимости'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_l_color',
            field=models.CharField(blank=True, default='льготный', help_text='Текст под льготной стоимостью будет выделен красным цветом', max_length=12, null=True, verbose_name='Особый текст'),
        ),
        migrations.AlterField(
            model_name='cardsprices',
            name='price_l_label',
            field=models.CharField(blank=True, default='р/ч', help_text='Единица измерения оплачиваемого времени, например: р/ч, р/д', max_length=5, null=True, verbose_name='Ярлык льготной стоимости'),
        ),
    ]
