# Generated by Django 3.2.8 on 2022-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_auto_20220130_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsobject',
            name='icons',
            field=models.FilePathField(blank=True, path='staticfiles/icons', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='cardsobject',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Интернет ссылка'),
        ),
    ]
