# Generated by Django 3.2.8 on 2022-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_auto_20220130_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsobject',
            name='color',
            field=models.CharField(choices=[('--city', 'малиновый'), ('--ski', 'голубой'), ('--beach', 'оранжевый'), ('--camping', 'зеленый')], default='--city', max_length=15, verbose_name='Цвет'),
        ),
    ]
