# Generated by Django 3.2.8 on 2022-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0043_alter_cardsprices_price_f_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_title', models.CharField(max_length=50, null=True, verbose_name='Фронтальный заголовок')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=400, null=True, verbose_name='Текст')),
                ('publish', models.BooleanField(verbose_name='Опубликовать')),
                ('imgAdd', models.ImageField(blank=True, upload_to='staticfiles/img/news', verbose_name='Добавить фото')),
                ('imgChoice', models.FilePathField(blank=True, path='staticfiles/img/news', verbose_name='Выбрать фото')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'get_latest_by': ['id'],
            },
        ),
    ]
