# Generated by Django 3.2.8 on 2022-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_auto_20220201_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=15, null=True, verbose_name='Должность')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Факс')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='Примечания')),
                ('publish', models.BooleanField(verbose_name='Опубликовать')),
                ('imgAdd', models.ImageField(blank=True, upload_to='staticfiles/img/news', verbose_name='Добавить фото')),
                ('imgChoice', models.FilePathField(blank=True, path='staticfiles/img/news', verbose_name='Выбрать фото')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['position'],
            },
        ),
    ]
