# Generated by Django 3.2.8 on 2022-02-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_auto_20220201_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achieves',
        ),
    ]
