# Generated by Django 3.2.8 on 2022-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0048_delete_achieves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achieves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=70, null=True, verbose_name='Описание')),
                ('publish', models.BooleanField(verbose_name='Опубликовать')),
                ('imgAdd', models.ImageField(blank=True, upload_to='staticfiles/img/cup', verbose_name='Добавить фото')),
                ('imgChoice', models.FilePathField(blank=True, path='staticfiles/img/cup', verbose_name='Выбрать фото')),
                ('imgAdd_award', models.ImageField(blank=True, upload_to='staticfiles/img/cup', verbose_name='Добавить фото награды')),
                ('imgChoice_award', models.FilePathField(blank=True, path='staticfiles/img/cup', verbose_name='Выбрать фото награды')),
            ],
            options={
                'verbose_name': 'Слайдер достижения',
                'verbose_name_plural': 'Слайдеры достижения',
                'ordering': ['-id'],
            },
        ),
    ]
