# Generated by Django 3.2.8 on 2022-02-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0049_achieves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieves',
            name='description',
            field=models.TextField(max_length=140, null=True, verbose_name='Описание'),
        ),
    ]
