# Generated by Django 3.2.8 on 2022-02-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_alter_achieves_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieves',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
