# Generated by Django 3.2.8 on 2022-02-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0052_auto_20220202_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsobject',
            name='inside_title',
        ),
    ]
