# Generated by Django 3.2.8 on 2022-02-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0053_remove_cardsobject_inside_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsobject',
            name='inside_title',
            field=models.CharField(max_length=35, null=True, verbose_name='Внутренний заголовок'),
        ),
        migrations.AlterField(
            model_name='achieves',
            name='title',
            field=models.CharField(max_length=70, null=True, verbose_name='Заголовок'),
        ),
    ]
