# Generated by Django 3.2.8 on 2022-02-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0054_auto_20220202_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieves',
            name='title',
            field=models.CharField(max_length=35, null=True, verbose_name='Заголовок'),
        ),
    ]
