# Generated by Django 3.2.8 on 2022-02-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0055_alter_achieves_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['rang'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='rang',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ранг'),
        ),
    ]
