# Generated by Django 3.2.8 on 2022-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0057_alter_contact_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieves',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='objectaddres',
            name='publish',
            field=models.BooleanField(default=True, help_text='разместить контакты в footer', verbose_name='Опубликовать'),
        ),
    ]
